apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexthouse-chat
  labels:
    app: nexthouse-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexthouse-chat
  template:
    metadata:
      labels:
        app: nexthouse-chat
    spec:
      containers:
      - name: nexthouse-chat
        image: eastshine96/nexthouse-chat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8889
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: nexthouse-chat-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nexthouse-chat-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: nexthouse-chat-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: nexthouse-chat-config
              key: DB_PASSWORD
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: nexthouse-chat-config
              key: SERVLET_CONTEXT_PATH
